apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: artifactory-test-quarkus 
  janus-idp.io/tekton: artifactory-test-quarkus
  backstage.io/kubernetes-id: artifactory-test-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: artifactory-test-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  