apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: artifactory-test-quarkus-gitops
  description: This is GitOps manifest for artifactory-test-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: artifactory-test-quarkus
    backstage.io/kubernetes-id: artifactory-test-quarkus 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: artifactory-test-quarkus   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:artifactory-test-quarkus
