apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: artifactory-test-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: artifactory-test-quarkus 
  name: artifactory-test-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: artifactory-test-quarkus 
